from elasticsearch import Elasticsearch
 
# Connect to the elastic cluster
# Password for the 'elastic' user generated by Elasticsearch
es = Elasticsearch("https://elastic:ba1u**GF*n4_wcgy0ETO@localhost:9200",
                    ca_certs="/Users/liuxg/elastic/elasticsearch-8.2.0/config/certs/http_ca.crt",
                    verify_certs=True)

print(es)
es.info()

analyzers = ["english", "standard", "simple", "whitespace", "stop", "keyword", "pattern", "fingerprint"]

for analyzer in analyzers:
    res = es.indices.analyze( analyzer = analyzer, text = ["This is Xiaoguo Liu from Beijing China, and I am developer.100"])
    tokens = [ sample['token'] for c, sample in enumerate(res['tokens']) ]
    print("\n")
    print("Analyzer : {}".format(analyzer))
    print('tokens: {}'.format([sample['token'] for c, sample in enumerate(res['tokens'])]))
    print(len([sample['token'] for c, sample in enumerate(res['tokens'])]))    
